### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by wujunjie1998** [zijwang/genderperformr#1]
Hi:

Thanks for your great work! It seems that your package will encounter a bug under pytorch1.7 or higher versions. The error information is:
AttributeError: module 'torch.utils.data' has no attribute 'BatchSamplerDistributedSamplerDataset'

which has been discussed here[https://discuss.pytorch.org/t/torch-utils-data-issue-with-v1-7/101944 ](url)
Could you take a look at this?

Thanks!

**Comment by zijwang** [comment]
Hi Junjie! Could you check the PR #2 and see whether it works now?

**Comment by wujunjie1998** [comment]
Hi Zijian, it works fine now! You could update the corresponding python package in your free time. Thanks!

**Comment by zijwang** [comment]
Thanks. It's on pypi now.
